homeassistant: 
  # Name of the location where Home Assistant is running
  name: Home
 # Location required to calculate the time the sun rises and sets
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 130
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


#sensor:
#  - platform: mqtt
#    name: Zigbee2mqtt Networkmap
#    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
#    state_topic: zigbee2mqtt/bridge/networkmap/raw
#    value_template: >-
#      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
#    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
#    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

ios:
  push:
    categories:
      - name: Sump Pump iOS Action
        identifier: 'sumppumpiosaction'
        actions:
          - identifier: 'PUMP_NOW_2MIN'
            title: 'Pump for 2mins'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
          - identifier: 'IGNORE_24H'
            title: 'Ignore until tomorrow'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
logger:
  default: info
  logs:
#    homeassistant.components.temper: debug
#    homeassistant.components.temper.sensor: debug
#    homeassistant.components.aurora_abb_powerone: debug
#    homeassistant.components.aurora_abb_powerone.sensor: debug
#    homeassistant.util.package: debug
#    homeassistant.components.binary_sensor: debug
#    homeassistant.components.device_tracker: debug

#    homeassistant.core: debug
#    homeassistant.components.sensor.command_line: warning
    custom_components: debug
    custom_components.bwio: info

# Discover some devices automatically
discovery:

# Sensors
sensor: 
  - platform: mqtt 
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw 
    value_template: >- 
        {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

  # Weather prediction
  - platform: yr
    name: Weather
    forecast: 0 # current weather, change to 24 for 24h forecast.
    #expire_after:
    monitored_conditions:
      - temperature
      - humidity
      - symbol
      - precipitation
      - dewpointTemperature
#  - platform: temper
#    name: Subfloor
  - platform: aurora_abb_powerone
    device: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0'
    #address: 2
# Miflora is temporarily broken or out of range of our bluetooth dongle - oct2019
#  - platform: miflora
#    mac: 'C4:7C:8D:6A:09:EE'
#    name: "miflora1"
#    #median: 3
#    monitored_conditions:
#      - moisture
#      - light
#      - temperature
#      - conductivity
#      - battery
  - platform: mqtt
    state_topic: "home/kitchen/catflap"
    name: catflap
    icon: mdi:cat
    expire_after: 43200 #43200=12h
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw
  - platform: mqtt
    state_topic: "home/subfloor/waterdepth"
    name: sump
    unit_of_measurement: "mm"
    icon: mdi:cup-water
    payload_not_available: "#"
    value_template: "{{ value|int('unknown') }}"
    expire_after: 3600 #3600=1h 
  - platform: mqtt
    state_topic: "home/subfloor/temperature"
    name: subfloor_temp
    unit_of_measurement: "°C"
    device_class: temperature
#    icon: mdi:cup-water
    payload_not_available: "#"
    value_template: "{{ value|float('unknown') }}"
    expire_after: 3600 #3600=1h 
  - platform: mqtt
    state_topic: "home/subfloor/rh"
    name: subfloor_rh
    device_class: humidity
    unit_of_measurement: "%"
#    icon: mdi:cup-water
    payload_not_available: "#"
    value_template: "{{ value|float('unknown') }}"
    expire_after: 3600 #3600=1h 
  - platform: mqtt 
    state_topic: "home/subfloor/dewpoint" 
    name: subfloor_dewpoint 
    unit_of_measurement: "°C" 
    device_class: temperature
#    icon: mdi:cup-water
    payload_not_available: "#" 
    value_template: "{{ value|float('unknown') }}"
    expire_after: 3600 #3600=1					


binary_sensor:
  - platform: ping
    host: !secret networkspace_hostname
    name: "Networkspace ping"
    count: 1
  - platform: ping
    host: !secret rpi2_hostname
    name: "RPi 2 ping"
    count: 1
  - platform: ping
    host: !secret rpi1_hostname
    name: "RPi 1 ping"
    count: 1
  - platform: ping
    host: 192.168.1.10
    name: "Driveway cam ping"
    count: 1
  - platform: ping
    host: 192.168.1.11
    name: "Treehouse cam ping"
    count: 1
  - platform: ping
    host: !secret router_hostname
    name: "ADSL router"
    count: 1
  - platform: ping
    host: now.tv
    name: "Internet"
    count: 1
  - platform: ping
    host: !secret hivehub_hostname
    name: "Hive Hub Local Ping"
    count: 1
#  - platform: command_line
#    command: 'lsusb | grep TEMPerHUM | wc -l'
#    name: 'USB TEMPerHUM Sensor'
#    device_class: connectivity
#    payload_on: 1
#    payload_off: 0
  - platform: command_line
    command: 'lsusb | grep "Bluetooth Dongle" | wc -l'
    name: 'USB Bluetooth Dongle'
    device_class: connectivity
    payload_on: 1
    payload_off: 0
  - platform: command_line
    command: 'lsusb | grep "FT232 Serial" | wc -l'
    name: 'USB RS485 Adaptor'
    device_class: connectivity
    payload_on: 1
    payload_off: 0
# Re-map several status indicators that don't have 'connectivity' device class
  - platform: template
    sensors:
      hive_online_status:
        friendly_name: "Hive Hub Internet Link"
        device_class: connectivity
        value_template: >-
          {% if is_state('sensor.hive_hub_status', 'Online') %}
            True
          {% else %}
            False
          {% endif %}
      zigbee2mqtt_bridge_online_status:
        friendly_name: "Zigbee2mqtt Bridge Status"
        device_class: connectivity
        value_template: >-
          {% if is_state('sensor.zigbee2mqtt_bridge_state', 'online') %}
            True
          {% else %}
            False
          {% endif %}

light:
  - name: "Hall"
    platform: mqtt
    command_topic: "/energenie/ENER002/1036640/3"
    payload_on: "On"
    payload_off: "Off"

switch:
  - name: "Sump pump"
    platform: mqtt
    command_topic: "/energenie/ENER002/1036640/2"
    icon: mdi:water-pump
    payload_on: "On"
    payload_off: "Off"

fan:
  - name: "Subfloor"
    platform: mqtt
    command_topic: "/energenie/ENER002/1036640/1"
    payload_on: "On"
    payload_off: "Off"

plant:
  #"Citrorfotunella microcarpa"
  citrofortunella_microcarpa:
    sensors:
      moisture: sensor.miflora1_moisture
      battery: sensor.miflora1_battery
      temperature: sensor.miflora1_temperature
      conductivity: sensor.miflora1_conductivity
      brightness: sensor.miflora1_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 17
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 6
    max_temperature: 35
    min_brightness: 4000
    max_brightness: 65000
    
media_player:
  - platform: panasonic_viera
    host: !secret panasonictv_hostname
    #mac: 20:C6:EB:C7:CB:0E - no benefit to adding the mac - WOL unsupported.
  
hive:
  username: !secret hive_username
  password: !secret hive_password

# Text to speech
tts:
  - platform: google_translate

camera:
  - platform: generic
    stream_source: !secret ipcam_driveway_streamsource
    still_image_url: !secret ipcam_driveway_stillimageurl
    authentication: digest
    username: !secret ipcam_username
    password: !secret ipcam_password
    name: Driveway
  - platform: generic
    stream_source: !secret ipcam_treehouse_streamsource
    still_image_url: !secret ipcam_treehouse_stillimageurl
    authentication: digest
    username: !secret ipcam_username
    password: !secret ipcam_password
    name: Treehouse

device_tracker:
  - platform: bluetooth_tracker

mqtt:
    broker: localhost
    client_id: hass
    username: !secret mqtt_username
    password: !secret mqtt_password
    discovery: true
    discovery_prefix: homeassistant
    birth_message:
      topic: 'hass/status'
      payload: 'online'
    will_message:
      topic: 'hass/status'
      payload: 'offline'


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
